git pre commit added

diff --git a/.github/hooks/pre-commit b/.github/hooks/pre-commit
--- a/.github/hooks/pre-commit
+++ b/.github/hooks/pre-commit
@@ -1,22 +1,58 @@
 #!/bin/bash
+# axe DevTools Linter pre-commit
+# This script will setup the environment variables needed for axe-linter-connector
+# and execute axe-linter-connector. The output file will be reviewed and call back with exit codes:
+## 0 - No Accessibility Defects
+## 1 - axe DevTools Linter Detected Accessibility Defects
+## 2 - Execution problem, or axe DevTools Linter unavailable.
+ 
+echo "axe DevTools Linter Starting $(date)"
+ 
+# Setup variables for axe DevTools Linter
+export AXE_LINTER_SERVER_URL=http://localhost
+export AXE_LINTER_SERVER_PORT=3000
+StatusCode=0
 
-# This is a sample pre-commit hook script.
-
-# You can customize it to run any checks or commands you need.
-
-# For example, you can check for code style violations, run tests,
-# or lint your code.
-
-echo "Running pre-commit hook..."
-
-# Example: run a linter
-# eslint --fix --ext .js,.jsx,.ts,.tsx src/
-
-# Example: run unit tests
-# npm run test
-
-# Exit with a non-zero code if any of the checks fail
-if [ $? -ne 0 ]; then
-  echo "Pre-commit hook failed. Commit aborted."
-  exit 1
+if [[ -z "fb7ee15e-1598-4076-8685-e220a98d9c20" ]]; then
+   echo "AXE_LINTER_API_KEY must be set"
+   exit 2
 fi
+# Configure verbose output.
+VerboseOutput="false"
+# Configure outfile: output in Generic Issue Import Format for in execution directory.
+OutFile="axe-linter-report.json"
+for i in $(git status --porcelain | sed s/^...//); do
+   rm -f $OutFile
+   TempCode=0
+   shopt -s nocasematch;
+   if [[ $i == *.html ]] || [[ $i == *.js ]] || [[ $i == *.jsx ]]|| [[ $i == *.ts ]]|| [[ $i == *.tsx ]]|| [[ $i == *.vue ]]|| [[ $i == *.htm ]]|| [[ $i == *.md ]]|| [[ $i == *.markdown ]];
+   then
+      if $VerboseOutput; then
+         echo "Accessibility check: file: $i"
+      fi
+      # execute axe DevTools Linter Connector
+      axe-linter-connector -s $i -d . --api-key $AXE_LINTER_API_KEY --config ./axe-linter.yml --url $AXE_LINTER_SERVER_URL
+
+      if [ ! -f "$OutFile" ];then
+         echo "$OutFile Does Not Exist"
+         exit 2
+      elif cat "$OutFile" | grep -q "BUG"; then
+         if $VerboseOutput; then
+            cat $OutFile
+         fi
+         echo "**axe DevTools Linter Accessibility Issues Detected: $i"
+         TempCode=1
+      else
+         echo "No axe DevTools Linter Connector Issues Detected in: $i"
+      fi
+      if [ "$TempCode" != "0" ]; then
+         StatusCode=1
+      fi
+      rm $OutFile
+   fi
+done
+ 
+if [ "$StatusCode" != "0" ]; then
+   echo "Commit Failed due to Accessibility Issues"
+fi
+exit $StatusCode
